---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud9
  labels:
    name: cloud9
    app: cloud9
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: cloud9
  template:
    metadata:
      labels:
        name: cloud9
        app: cloud9
    spec:
      restartPolicy: Always
      shareProcessNamespace: true
      initContainers:
        - name: volume-permissions
          image: busybox
          command: ['sh', '-c', 'chmod -R a+rwX /app && chmod -R g+rw /var/run/docker.sock']
          volumeMounts:
          - mountPath: /app/workspace
            name: cloud9-storage
            subPath: data
            readOnly: true
          - mountPath: /var/run/docker.sock
            name: docker-sock
            readOnly: true
        - name: git-permissions
          image: busybox
          command: ['sh', '-c']
          args: ["export HOME=/app; git config --global credential.helper 'cache --timeout=300'; chmod -R a+rwX /app"]
          volumeMounts:
          - mountPath: /app/workspace
            name: cloud9-storage
            subPath: data
            readOnly: false
          - mountPath: /var/run/docker.sock
            name: docker-sock
            readOnly: true
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "20Mi"
              cpu: "20m"
          securityContext:
            readOnlyRootFilesystem: true
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_ADMIN
                - SYS_TIME
      containers:
        - image: saidsef/cloud9-containerised:latest
          name: cloud9
          ports:
            - protocol: TCP
              containerPort: 9099
              name: cloud980
          volumeMounts:
            - name: cloud9-storage
              mountPath: /app/workspace
              subPath: data
            - name: docker-sock
              mountPath: /var/run/docker.sock
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            exec:
              command:
                - pgrep
                - node
            failureThreshold: 2
            successThreshold: 1
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            tcpSocket:
                port: 9099
            failureThreshold: 2
            successThreshold: 1
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
          securityContext:
            readOnlyRootFilesystem: true
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_ADMIN
                - SYS_TIME
      volumes:
        - name: cloud9-storage
          emptyDir: {}
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: File
